### ISSUE TITLE
Opravit a doplnit .github/workflows/copilot-setup-steps.yml podle doporučení pro LangGraph Studio a Copilot Agent

### ISSUE THREAD

**Issue by minarovic** [minarovic/AI-agent-PoC3#36]
Aktuální soubor `.github/workflows/copilot-setup-steps.yml` je prázdný nebo nevalidní (chybí root klíč `steps`). Je potřeba jej upravit tak, aby odpovídal doporučením GitHub Copilot Agent a LangGraph Platform.

**Konkrétní úkoly:**
- Doplnit root klíč `steps:`.
- Přidat kroky pro instalaci pouze produkčních závislostí (`pip install -r requirements.txt`), nikoliv testovacích/development závislostí.
- Nastavit správnou verzi Pythonu (3.11) přes `actions/setup-python`.
- Nastavit proměnnou prostředí `PYTHONPATH` na `${{ github.workspace }}/src`.
- Výsledný YAML soubor má vypadat následovně:

```yaml
steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  - name: Install production dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Set PYTHONPATH
    run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV
```

**Poznámky:**
- Nepřidávat testovací ani linter závislosti.
- Nepoužívat FastAPI/uvicorn, pokud není potřeba.
- Výsledný soubor musí být validní YAML a začínat root klíčem `steps:`.

Viz doporučení na základě:
- https://docs.github.com/en/enterprise-cloud@latest/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent
- https://docs.langchain.com/langgraph/docs/platform/deployment/
